### ISSUE TITLE
Shader Model 6.6 + Windows 10 (Agility SDK)

### ISSUE THREAD

**Issue by JustAndreww** [AnisB/large_cbt#1]
Hello!

Looks like this demo is intended to work only with Windows 11? Is it possible to compile and link with Agility SDK directly (and ship d3d12core.dll in the build package)?

https://devblogs.microsoft.com/directx/gettingstarted-dx12agility/

Thanks!

**Comment by AnisB** [comment]
I kept the code base light for the initial release, I'll add th agility SDK at the next release i'll do

**Comment by BenjaCorp** [comment]
ha yeah that would be really nice, Thanks

**Comment by AnisB** [comment]
You can find the 1.1 release here that uses the latest agility SDK
https://github.com/AnisB/large_cbt/releases/tag/release_1.1

**Comment by AnisB** [comment]
Closing

**Comment by AnisB** [comment]
Closing
